### ISSUE TITLE
Channel Permission Bug

### ISSUE THREAD

**Issue by Pocanistaken** [DiSkyOrg/DiSky#51]
Hey when i try to add permissions in channel to members or roles there is a big problem. It's always just adding latest permission to member / roles

```
    set {_memberpermission::*} to yaml list "Options.Ticket.Permissions.Event-Member.Permission" from "config" 
    loop {_memberpermission::*}:
        add (loop-value parsed as permission) to permissions of {_member} in {_channel}

```
![image](https://user-images.githubusercontent.com/51020037/173232502-fdc6ce79-aab5-473b-8518-ef628445aaf5.png)

For example in this code as you can see latest permission on the list = message attach files so it's just adding the message attach

![image](https://user-images.githubusercontent.com/51020037/173232483-42a44926-7be8-4866-9ba8-640f51de26f0.png)

Also when checking the server logs on the discord we can see it's adding all of them but after resetting it's like add after reset , add reset so there is a important bug i think.

After just talked with @Mushkrem 22.05.2022 and tell them this bug on after @Mushkrem changed somethings on the .jar after give it me when i try it was working on just one role and it was slow and delayed beacuse of the wait effects
```
function TicketCreateTicket(channelname : text, i : int, topic : text, categoryid : text, guild : guild, member : member):
    set {_action} to new text channel action in {_guild}
    set channel parent of {_action} to category with id {_categoryid}
    set channel name of {_action} to "%{_channelname}%-%{_i}%"
    set topic of {_action} to "%{_topic}%"
    create {_action} and store it in {_channel}
    remove (view channel) from permissions of public role of {_guild} in {_channel}
    
    set {_eventmemberpermission::*} to yaml list "Options.Ticket.Permissions.Event-Member" from "config"
    loop {_eventmemberpermission::*}:
        add (loop-value parsed as permission) to permissions of {_member} in {_channel} #Problem in here
        wait 1 seconds


    
    loop yaml node keys "Options.Ticket.Permissions.Roles" from "config":
        set {_permission::*} to yaml list "Options.Ticket.Permissions.Roles.%loop-value%" from "config" 
        loop {_permission::*}:
            add (loop-value-2 parsed as permission) to permissions of role with id loop-value-1 in {_channel} #Problem in here 
            wait 1 seconds
```

![image](https://user-images.githubusercontent.com/51020037/173232885-b4abd581-8848-40c6-b611-fb0f28af5267.png)

It's just adding permissions to the role with id "977891644932227142" correct after the second role still same problem just adding latest permission on the list only message attachments files.Im said @Mushkrem this problem @Mushkrem said

![image](https://user-images.githubusercontent.com/51020037/173233057-ee50857e-c234-4489-848c-74bb2624eff9.png)

Now i just think its beacuse of the yml list so i tried do it like that

```
    # Event-Member Permission
    add (view channel) to permissions of {_member} in {_channel}
    add (message send) to permissions of {_member} in {_channel}
    add (message add reaction) to permissions of {_member} in {_channel}
    add (message attach files) to permissions of {_member} in {_channel}
```
![image](https://user-images.githubusercontent.com/51020037/173233230-2f2e00f3-590b-4e84-9868-2b7f459e7a69.png)

But nothing changed beacuse it's still adds the only last specified permission as you can see with the discord logs

The channel permissions was working perfect on disky 2.1 but in the disky 4 there looks big problem.

I am open to your suggestions for a helpful solution if this is a bug or not, what is it?

**Comment by SkyCraft78** [comment]
Still not able to reproduce. However I'm parsing or setting a list with different permission, all of them are been added. 
I'll keep this issue open, but don't forget to tell us if you have any new behavior about it.

**Comment by Pocanistaken** [comment]
> Still not able to reproduce. However I'm parsing or setting a list with different permission, all of them are been added. I'll keep this issue open, but don't forget to tell us if you have any new behavior about it.

Ok im almost tried every way but can't fixed it

**Comment by Pocanistaken** [comment]
Wrongly closed sorry.
I'm almost tried every way but can't fix it.

**Comment by wallace4BR** [comment]
> Wrongly closed sorry. I'm almost tried every way but can't fix it.

Can you try the new build at actions?

**Comment by Pocanistaken** [comment]
I'm trying it wait.

**Comment by Pocanistaken** [comment]
Latest build got problems

Log-> https://paste.helpch.at/olilecitih.md

**Comment by wallace4BR** [comment]
> Latest build got problems
> 
> Log-> https://paste.helpch.at/olilecitih.md

@SkyCraft78

**Comment by SkyCraft78** [comment]
Is there any news for that, using DiSky 4.1.0?

**Comment by wallace4BR** [comment]
I guess that could be fixed by using `putPermissionOverride` instead of `upsertPermissionOverride` but i'm unable to test anyway

**Comment by SkyCraft78** [comment]
`putPermissionOverride` has been removed since some times already

**Comment by SkyCraft78** [comment]
@Pocanistaken Could you try with the new artifact that will be built soon, please?
I think I fixed your issue.

**Comment by wallace4BR** [comment]
> `putPermissionOverride` has been removed since some times already

not really, it stills exists in the channel manager

**Comment by SkyCraft78** [comment]
The problem should be fixed. Take a look at [this commit](https://github.com/DiSkyOrg/DiSky/commit/3236b8f777fa6366e8b908847fac15e7285c737c)

**Comment by SkyCraft78** [comment]
@Pocanistaken Any news? I'm gonna close this issue, feel free to open it again if the problem is still there after the artifact update.

**Comment by Pocanistaken** [comment]
Disky still have this issue it's looks don't fixed but im fixed it with skript-reflect here is the code no delay no bug + fast

```
	set {_perm} to new ArrayList()
	set {_eventmemberpermission::*} to yaml list "Options.Ticket.Permissions.Event-Member" from "config"
	loop {_eventmemberpermission::*}:
		set {_parse} to Permission.valueOf(loop-value)
		{_perm}.add({_parse})

	{_channel}.upsertPermissionOverride({_member}).grant({_perm}).queue()
	
	set {_roleperm} to new ArrayList()
	loop yaml node keys "Options.Ticket.Permissions.Roles" from "config":
		set {_permission::*} to yaml list "Options.Ticket.Permissions.Roles.%loop-value%" from "config" 
		loop {_permission::*}:
			set {_roleparse} to Permission.valueOf(loop-value-2)
			{_roleperm}.add({_roleparse})
		broadcast "roles -> %loop-value%"
		set {_role} to role with id "%loop-value%"
		broadcast "role parsed id -> %{_role}%"
		{_channel}.getPermissionContainer().upsertPermissionOverride({_role}).grant({_roleperm}).queue()
		
```
